apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sokos-okosynk
  namespace: okonomi
  labels:
    team: okonomi
spec:
  groups:
    - name: sokos-okosynk-alerts
      rules:
        - alert: sokos-okosynk er nede
          expr: kube_deployment_status_replicas_available{deployment="sokos-okosynk"} == 0
          for: 2m
          annotations:
            action: "Sjekk hvorfor applikasjonen er nede"
            summary: "{{ $labels.deployment }} er nede i namespace {{ $labels.namespace }}"
          labels:
            namespace: okonomi
            severity: critical
            sokos_okosynk_type: sokos-okosynk
            alert_type: custom

        - alert: sokos-okosynk har restartet flere ganger de siste 5 minuttene!
          expr: sum(increase(kube_pod_container_status_restarts_total{container=~"sokos-okosynk"}[5m])) by (container) > 2
          for: 2m
          annotations:
            action: "Sjekk hvorfor applikasjonen ikke klarer å restarte"
            summary: "{{ $labels.container }} restarter mange ganger"
          labels:
            namespace: okonomi
            severity: critical
            sokos_okosynk_type: sokos-okosynk
            alert_type: custom

        - alert: Applikasjonen logger høy andel errors
          expr: |
            (sum_over_time(loki:service:loglevel:count1m{detected_level="error",service_name="sokos-okosynk"}[5m]) / sum_over_time(loki:service:loglevel:count1m{service_name="sokos-okosynk"}[5m])) > 0
          for: 2m
          annotations:
            action: "<https://grafana.nav.cloud.nais.io/a/grafana-lokiexplore-app/explore/service_name/sokos-okosynk/logs?patterns=%5B%5D&from=now-24h&to=now&var-filters=service_name%7C%3D%7Csokos-okosynk&var-ds=prod-gcp-loki&var-levels=detected_level%7C%3D%7Cerror|Sjekk error loggene i sokos-okosynk>"
            summary: "`kubectl logs -l app=sokos-okosynk -n okonomi` for logger"
          labels:
            namespace: okonomi
            severity: danger
            sokos_okosynk_type: sokos-okosynk
            alert_type: custom

        - alert: Applikasjonen logger høy andel warnings
          expr: |
            (sum_over_time(loki:service:loglevel:count1m{detected_level="warn",service_name="sokos-okosynk"}[5m]) / sum_over_time(loki:service:loglevel:count1m{service_name="sokos-okosynk"}[5m])) > 0
          for: 2m
          annotations:
            action: "<https://grafana.nav.cloud.nais.io/a/grafana-lokiexplore-app/explore/service_name/sokos-okosynk/logs?patterns=%5B%5D&from=now-24h&to=now&var-filters=service_name%7C%3D%7Csokos-okosynk&var-ds=prod-gcp-loki&var-levels=detected_level%7C%3D%7Cwarn|Sjekk warning loggene i sokos-okosynk>"
            summary: "`kubectl logs -l app=sokos-okosynk -n okonomi` for logger"
          labels:
            namespace: okonomi
            severity: warning
            sokos_okosynk_type: sokos-okosynk
            alert_type: custom

---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: sokos-okosynk-slack
  namespace: okonomi
  labels:
    alertmanagerConfig: sokos-okosynk-slack
spec:
  receivers:
    - name: sokos-okosynk-receiver
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: '#team-mob-alerts-prod'
          iconEmoji: ':alert:'
          username: 'Alert prod-gcp (sokos-okosynk)'
          sendResolved: true
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts }}
            {{ if or .Annotations.summary .Annotations.message }}
            {{ or .Annotations.summary .Annotations.message }}
            {{ println " " }}
            {{- end }}
            {{- if .Annotations.action }}
            • *action*: {{ .Annotations.action }} {{ println " " }}
            {{- end }}
            {{ end }}
  route:
    groupBy:
      - alertname
    matchers:
      - name: "sokos_okosynk_type"
        matchType: "="
        value: "sokos-okosynk"
    groupInterval: 10s
    groupWait: 5s
    receiver: sokos-okosynk-receiver
    repeatInterval: 10m
