apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-okosynk
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  ingresses:
    - https://sokos-okosynk.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  webproxy: true
  filesFrom:
    - secret: okosynk-sftp-private-key
      mountPath: /var/run/secrets/okosynk-sftp-private-key
  env:
    - name: SCHEDULER_CRON_EXPRESSION
      value: "0 0 12 * * *"
    - name: SCHEDULER_ENABLED
      value: "true"

    # PDL
    - name: PDL_URL
      value: "https://pdl-api.intern.nav.no"
    - name: PDL_SCOPE
      value: "api://prod-fss.pdl.pdl-api/.default"

    # OPPGAVE
    - name: OPPGAVE_URL
      value: "https://oppgave.nais.adeo.no"
    - name: OPPGAVE_SCOPE
      value: "api://prod-fss.oppgavehandtering.oppgave/.default"

    # SFTP
    - name: SFTP_SERVER
      value: a01drvl100.adeo.no
    - name: SFTP_USERNAME
      value: srvOkosynk
    - name: SFTP_PORT
      value: "22"
    - name: SFTP_PRIVATE_KEY
      value: /var/run/secrets/okosynk-sftp-private-key/SFTP_PRIVATE_KEY