apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-okosynk
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 2000m
      memory: 4096Mi
  ingresses:
    - https://sokos-okosynk.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/metrics
  secureLogs:
    enabled: true
  filesFrom:
    - secret: okosynk-sftp-private-key
      mountPath: /var/run/secrets/okosynk-sftp-private-key
  env:
    - name: USE_AUTHENTICATION
      value: "true"

    - name: SCHEDULER_CRON_EXPRESSION
      value: "0 0 4 * * *"

    # PDL
    - name: PDL_URL
      value: "https://pdl-api-q1.dev.intern.nav.no"
    - name: PDL_SCOPE
      value: "api://dev-fss.pdl.pdl-api-q1/.default"

    # OPPGAVE
    - name: OPPGAVE_URL
      value: "https://oppgave-q1.dev.intern.nav.no"
    - name: OPPGAVE_SCOPE
      value: "api://dev-fss.oppgavehandtering.oppgave-q1/.default"

    # SFTP
    - name: SFTP_SERVER
      value: b27drvl011.preprod.local
    - name: SFTP_USERNAME
      value: srvOkosynk
    - name: SFTP_PORT
      value: "22"