name: Deploy application manual

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - dev
          - prod

env:
  TZ: Europe/Oslo

permissions:
  contents: "write"
  id-token: "write"

jobs:
  build:
    name: Build/test & push image
    uses: navikt/mob-gha-workflows/.github/workflows/gradle-build-push-image.yaml@main
    secrets: inherit
    with:
      gradle-task: './gradlew build installDist --configuration-cache'
      image-tag: snapshot

  deploy-fss:
    needs: build
    name: Deploy to ${{ inputs.environment }}-fss
    uses: navikt/mob-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: ${{ inputs.environment }}-fss
      resource: .nais/naiserator-${{ inputs.environment }}.yaml
      image: ${{ needs.build.outputs.image }}